const ZERO = 0;
const MIN_LENGTH_ONE   = 1;
const MIN_LENGTH_FOUR  = 4;
const MIN_LENGTH_EIGHT = 8;
const MIN_LENGTH_FIVE  = 5;
const MAX_LENGTH_FIFTY = 50;

const MAX_LENGTH_TWENTY         = 20;
const MAX_LENGTH_TWO_FIFTY_FIVE = 255;

const MAX_LENGTH_ONE_THOUSAND_TWENTY_FOUR = 1024;

const STATUS_CODE_OK = 200;
const STATUS_CODE_CREATED = 201;
const STATUS_CODE_BAD_REQUEST = 400;
const STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
const STATUS_CODE_UNAUTHORIZED = 401;
const STATUS_CODE_NOT_FOUND = 404;
const STATUS_CODE_FORBIDDEN = 403;
const EXPIRES_IN_ONE_HOUR = '1h';


module.exports = {
    ZERO,
    MIN_LENGTH_ONE,
    MIN_LENGTH_FOUR,
    MIN_LENGTH_EIGHT,
    MIN_LENGTH_FIVE,
    MAX_LENGTH_FIFTY,
    MAX_LENGTH_TWENTY,
    MAX_LENGTH_TWO_FIFTY_FIVE,
    MAX_LENGTH_ONE_THOUSAND_TWENTY_FOUR,
    STATUS_CODE_OK,
    STATUS_CODE_BAD_REQUEST,
    STATUS_CODE_INTERNAL_SERVER_ERROR,
    STATUS_CODE_UNAUTHORIZED,
    STATUS_CODE_NOT_FOUND,
    STATUS_CODE_FORBIDDEN,
    STATUS_CODE_CREATED,
    EXPIRES_IN_ONE_HOUR
    };